## Estudando um pouco de numpy, scipy e PyTorch


In [3]:
import numpy as np

lista = list(range(6))

x = np.array(lista)

print(x)

# Retorna uma tupla com o tamanho das dimensões do array.
print(x.shape)

[0 1 2 3 4 5]
(6,)


In [43]:
# Cria uma matrix dado os inputs
A = np.matrix('0 1 2 4; 3 4 5 5; 6 7 8 6')
print(A)

[[0 1 2 4]
 [3 4 5 5]
 [6 7 8 6]]


In [5]:
# Cria uma matrix identidade de tamanho 4x4.
I4 = np.identity(4)
print(I4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# Multiplicação entre matrizes m x p * p *n  onde p==p

np.matmul(A, I4)

matrix([[0., 1., 2., 4.],
        [3., 4., 5., 5.],
        [6., 7., 8., 6.]])

In [9]:
# Cria um array do numpy
np.arange(9)

[0 1 2 3 4 5 6 7 8]
[ 2  3  4  5  6  7  8  9 10]


In [ ]:
# Adiciona 2 para cada valor do array do numpy
print(np.arange(9) + 2) # broadcasting

In [44]:
X = np.arange(9)
print(X)
# Muda a forma do array, no caso, antes era um array 1x9 (uma linha e nove coluna)
# após a operação será uma array de 3x3 (3 linhas e 3 colunas).
B = np.arange(9).reshape((3,3))
print(B)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
# Matrix-Matrix Multiplication
aux = np.arange(12).reshape(4, 3)
print(aux)

print(B)

C = np.matmul(aux,B)
print(C)


print("Outra forma de multiplicar matrix:")
print(aux * B)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [54]:

# retorna a diagonal da matrix
np.diag(C)

array([ 15,  54, 111])

In [58]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
# elementwise ou Hadamard product (matrices)
# note que * é diferente de matmult !!!! é necessário 
# que A e B tenham o mesmo tamanho
print(A * B)     


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [67]:
# As duas operações são equivalentes:
print(np.matmul(A, B))

print(A @ B)

print(A.dot(B))


[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [68]:
# As duas operações são equivalentes:
A = np.array([[ 5, 1 ,3], 
              [ 1, 1 ,1], 
              [ 1, 2 ,1]])

x = np.array([1, 2, 3])

print(np.matmul(A, x))

print(A @ x)

print(A.dot(x))


[16  6  8]
[16  6  8]
[16  6  8]


In [64]:
# Retorna o produto interno(inner product)
# <x,y> = <(1, 2, 3), (0, 1, 0)> = 1*0 + 2*1 + 3*0 = 2
x = np.array([1,2,3])
y = np.array([0,1,0])



np.inner(x, y)

2

In [65]:
# Cria uma matrix identidade
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [66]:
# Retorna um novo array preenchido com 1s a
# partir de um shape(formato da matrix)
np.ones((3,))

array([1., 1., 1.])

In [ ]:
# outer product
x = np.ones((5,))
print(x)

y = np.linspace(-2, 2, 5)
print(y)

# retorna o produto externo(vetorial)(outer product)
np.outer(x, y)

In [69]:
aux = np.eye(3)
print(aux)

# Retorna o somatório da diagonal
np.trace(aux)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3.0

In [71]:
# vector norms
from numpy import linalg as LA

print(LA.norm(aux))


1.7320508075688772


In [74]:
import torch

help(torch.empty)
torch.empty(2, 2)

Help on built-in function empty:

empty(...)
    empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format) -> Tensor
    
    Returns a tensor filled with uninitialized data. The shape of the tensor is
    defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device o

tensor([[-6.7995e-14,  4.5639e-41],
        [-6.7995e-14,  4.5639e-41]])